### ISSUE TITLE
Possible conflict with NuclearCraft

### ISSUE THREAD

**Issue by kreezxil** [blay09/RefinedRelocation2#20] opened 2017-05-26 18:14 UTC
https://github.com/turbodiesel4598/NuclearCraft/issues/108

**Comment by kreezxil** [comment] 2017-05-26 18:15
We placed a fission controller and now our server is in a crash loop. the fission controller is from NuclearCraft, but refined relocation's fast hopper is implicated the crash report.

https://gist.github.com/778e93b979f9a75d837c873e4359d1c0

**Comment by BlayTheNinth** [comment] 2017-05-26 18:21
Looks like something corrupted that chunk, the game thinks there's a Fast Hopper at the position the Fission Reactor was placed.

```
-- Block entity being ticked --
Details:
	Name: refinedrelocation:fast_hopper // net.blay09.mods.refinedrelocation.tile.TileFastHopper
	Block type: ID #2052 (tile.fission_controller_active // nc.block.tile.generator.BlockFissionController)
```

You may be able to get it to stop crashing by enabling the `remove erroring tile entities` option in the forge.cfg

**Comment by kreezxil** [comment] 2017-05-26 18:28
thanks I'll give that a try

**Comment by BlayTheNinth** [comment] 2017-05-28 19:36
Is this reproducible or is it no longer happening now?

**Comment by kreezxil** [comment] 2017-05-28 19:38
Your suggestion didn't work. I removed nuclearcraft instead.

**Comment by BlayTheNinth** [comment] 2017-08-08 19:29
Closing this since it seems to be just normal world corruption and no one else so far encountered this problem.

**Closed as completed by BlayTheNinth** 2017-08-08 19:29 UTC
